name: TypeScript Check

on:
  push:
    branches: [ main, develop, fix/* ]
  pull_request:
    branches: [ main ]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install workspace dependencies
      run: npm install --workspaces
    
    # Use the CI-specific typecheck that ensures clean build
    - name: Run TypeScript checks
      run: npm run typecheck:ci
    
    # Ensure typecheck actually fails on errors
    - name: Verify TypeScript strict mode
      run: |
        cd packages/server && npx tsc --noEmit
        cd ../shared && npx tsc --noEmit